<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Question::count() === 0) {
            DB::table('questions')->insert([
                [
                    'question_en' => 'What is your full name?',
                    'question_another_lang' => 'আপনার পূর্ণ নাম কি?',
                    'field_type' => 'input',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 1,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Please select your gender',
                    'question_another_lang' => 'অনুগ্রহ করে আপনার লিঙ্গ নির্বাচন করুন',
                    'field_type' => 'radio-button',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 2,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'What is your age?',
                    'question_another_lang' => 'আপনার বয়স কত?',
                    'field_type' => 'input',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 3,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Select your preferred programming languages',
                    'question_another_lang' => 'আপনার পছন্দের প্রোগ্রামিং ভাষা নির্বাচন করুন',
                    'field_type' => 'checkbox',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 4,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Describe your work experience',
                    'question_another_lang' => 'আপনার কাজের অভিজ্ঞতা বর্ণনা করুন',
                    'field_type' => 'textarea',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 5,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Choose your country',
                    'question_another_lang' => 'আপনার দেশ বেছে নিন',
                    'field_type' => 'dropdown',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 6,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Select multiple skills you possess',
                    'question_another_lang' => 'আপনার যে দক্ষতাগুলি রয়েছে তা নির্বাচন করুন',
                    'field_type' => 'multiselect',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 7,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Record your introduction',
                    'question_another_lang' => 'আপনার পরিচয় রেকর্ড করুন',
                    'field_type' => 'voice_recorder',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 8,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Upload a video presentation',
                    'question_another_lang' => 'একটি ভিডিও উপস্থাপনা আপলোড করুন',
                    'field_type' => 'video_recorder',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 9,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Upload your resume',
                    'question_another_lang' => 'আপনার জীবনবৃত্তান্ত আপলোড করুন',
                    'field_type' => 'file_upload',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 10,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Select your experience level',
                    'question_another_lang' => 'আপনার অভিজ্ঞতার স্তর নির্বাচন করুন',
                    'field_type' => 'range',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 11,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Rate our service from 1 to 10',
                    'question_another_lang' => '১ থেকে ১০ পর্যন্ত আমাদের সেবার মূল্যায়ন করুন',
                    'field_type' => 'rating_number',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 12,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Provide feedback about our service',
                    'question_another_lang' => 'আমাদের সেবা সম্পর্কে প্রতিক্রিয়া প্রদান করুন',
                    'field_type' => 'rating_feedback',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 13,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Rate us with stars',
                    'question_another_lang' => 'তারকা দিয়ে আমাদের মূল্যায়ন করুন',
                    'field_type' => 'rating_star',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 14,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'How do you feel about our service?',
                    'question_another_lang' => 'আমাদের সেবা সম্পর্কে আপনি কেমন অনুভব করেন?',
                    'field_type' => 'rating_emoji',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 15,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Rate our customer support',
                    'question_another_lang' => 'আমাদের গ্রাহক সহায়তার মূল্যায়ন করুন',
                    'field_type' => 'rating_custom',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 16,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'What is your phone number?',
                    'question_another_lang' => 'আপনার ফোন নম্বর কত?',
                    'field_type' => 'input',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 17,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Record a general message',
                    'question_another_lang' => 'একটি সাধারণ বার্তা রেকর্ড করুন',
                    'field_type' => 'recorder',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 18,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Select your education level and specialization',
                    'question_another_lang' => 'আপনার শিক্ষার স্তর এবং বিশেষীকরণ নির্বাচন করুন',
                    'field_type' => 'combo',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 19,
                    'status' => true,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question_en' => 'Do you agree to our terms and conditions?',
                    'question_another_lang' => 'আপনি কি আমাদের নিয়মাবলী এবং শর্তাবলীতে সম্মত?',
                    'field_type' => 'checkbox',
                    'options' => null,
                    'score_range' => null,
                    'ref_id' => null,
                    'parent_id' => null,
                    'order' => 20,
                    'status' => false,
                    'created_by' => 1,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}